---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/term
  label: Termos
  create: documents
  match: "**/*"
  templates:
  - termo
- type: directory
  path: contant/text
  label: Textos
  create: documents
  match: "**/*"
  templates:
  - texto
- type: directory
  path: content/post
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - post
upload_dir: media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
